### PR TITLE
Resolved path

### PR DESCRIPTION
**Pull request by GitScrum**
- Added pkg in root package.json for testing
  - posthtml
  - posthtml-bem
  - posthtml-each (not used in test)
  - posthtml-include
  - posthtml-style-to-file
- Added XO linter JS code style
- Added npm run script test

- Update tests
- Update .editorConfig (XO requres tab instead space)

- Fixed resolved path for cross OS (I`m using windows :))
- Fixed XO report error

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
:+1:  I'm personally a follow of [StandardJS](https://github.com/feross/standard) but this should have been added to pkg since no one magically knows that im using that in my editor as the default. :).

The differences between XO and Standard are not that big as its seems from a quick overlook of xo, as long as no ``` .configXYZ  ``` involved i'm fine with it.(although ``` ;  ```are nasty little things, in my opinion ;)).

Please feel free to add yourself to the README && package.json as a contributor if you PR something to any of the projects. Thats a naturalness here. I'm doing it while publishing this time.

**Comment by GitScrum** [comment]
I like that for webpack there xo-loader to standard yet. 
Thank.

**Comment by michael-ciniawsky** [comment]
You mean you prefer xo over standard during the fact that there is a loader for code style linting when bundling your assets?

**Comment by GitScrum** [comment]
Of course not :) its rules fit my style of writing. And I think it is not safe to use a semicolon and don't really like the indentation to two spaces. Enough still used XO.

**Comment by michael-ciniawsky** [comment]
yes :D i understand you prefer it in terms of personal code styling but whats meant by that post of yours which mentioned webpack?

**Pull request merged**
